apiVersion: v1
kind: Service
metadata:
  name: {{ template "citus-postgresql.fullname" . }}-master
  labels:
    app: {{ template "citus-postgresql.name" . }}-master
    chart: {{ template "citus-postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.superuser.port }}
    protocol: TCP
    name: psql
  clusterIP: None
  selector:
    app: {{ template "citus-postgresql.name" . }}-master
    release: {{ .Release.Name }}
