apiVersion: v1
kind: Service
metadata:
  name: {{ template "citus-postgresql.fullname" . }}-worker
  labels:
    app: {{ template "citus-postgresql.name" . }}-worker
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.superuser.port }}
    name: psql
  clusterIP: None
  selector:
    app: {{ template "citus-postgresql.name" . }}-worker
    release: {{ .Release.Name }}
