{{ if .Values.manager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.manager.serviceAccount.name }}
  labels:
    app: {{ template "citus-postgresql.name" . }}-manager
    chart: {{ template "citus-postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
  labels:
    app: {{ template "citus-postgresql.name" . }}-manager
    chart: {{ template "citus-postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/status"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
  labels:
    app: {{ template "citus-postgresql.name" . }}-manager
    chart: {{ template "citus-postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.manager.serviceAccount.name }}
  namespace: {{ .Values.manager.namespace }}
roleRef:
  kind: Role
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
---
{{ end }}
