apiVersion: v1
kind: Secret
metadata:
  name: {{ template "citus-postgresql.fullname" . }}-secret
  labels:
    app: {{ template "citus-postgresql.name" . }}
    chart: {{ template "citus-postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  superuser-username: {{ .Values.superuser.username | b64enc }}
  superuser-password: {{ .Values.superuser.password | b64enc }}
  superuser-database: {{ .Values.superuser.database | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "citus-postgresql.fullname" . }}-pgpass
  labels:
    app: {{ template "citus-postgresql.name" . }}
    chart: {{ template "citus-postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  .pgpass: |-
    {{ template "citus-postgresql.fullname" . }}-master-0.{{ template "citus-postgresql.fullname" . }}-master:{{ .Values.superuser.port }}:postgres:{{ .Values.superuser.username }}:{{ .Values.superuser.password }}
    {{- $password := .Values.superuser.password -}}
    {{- $username := .Values.superuser.username -}}
    {{- $worker_port := .Values.superuser.port -}}
    {{- range $i, $e := until (int .Values.worker.replicaCount) }}
    {{ template "citus-postgresql.fullname" $ }}-worker-{{ $i }}.{{ template "citus-postgresql.fullname" $ }}-worker:{{ $worker_port }}:postgres:{{ $username }}:{{ $password }}
    {{- end -}}
{{- if .Values.ssl.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "citus-postgresql.fullname" . }}-ssl
  labels:
    app: {{ template "citus-postgresql.name" . }}
    chart: {{ template "citus-postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  citus.key: {{ .Values.ssl.key }}
  citus.crt: {{ .Values.ssl.cert }}
{{- end }}
