apiVersion: v1
kind: Service
metadata:
  name: {{ template "citus-postgresql.fullname" . }}
  labels:
    app: {{ template "citus-postgresql.name" . }}
    chart: {{ template "citus-postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.superuser.port }}
    protocol: TCP
    name: psql
  selector:
    app: {{ template "citus-postgresql.name" . }}-master
    release: {{ .Release.Name }}
